version: '3'

services: 

  app:
    build: 
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: sh -c "npm install && node index.js"
    networks: 
      - node-network
    volumes: 
      - ./node:/usr/src/app
    tty: true
    ports: 
      - "3000"
    depends_on: 
       - db

  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    tty: true
    command: --innodb-use-native-aio=0
    volumes: 
     # - ./mysql:/var/lib/mysql
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: wesleywillians/nginx:prod
    container_name: nginx
    networks: 
      - node-network
    ports: 
      - "8080:80"
    

networks: 
  node-network:
    driver: bridge      
